plugins_dir:
  - _plugins-38
  - _plugins

i18n_dir:
  - _ttio_templates/bedrock/_locales
  - _ttio_templates/ivy/_locales
  - _locales

layouts_dir:
  - _ttio_templates/bedrock/_layouts
  - _ttio_templates/ivy/_layouts
  - _layouts
  
data_dir: 
  - _ttio_templates/bedrock/_data
  - _ttio_templates/ivy/_data
  - _data
  
includes_dir:
  - _includes
  - _ttio_templates/ivy/_includes
  - _ttio_templates/bedrock/_includes
  



# Site Settings
title: "IVY"
title_separator: "|"
name: "Hotel Property Name"
description: "Site default description."
url: # the base hostname & protocol for your site e.g. "https://www.traveltripper.io"
repository: "" # GitHub username/repo-name e.g. "TravelTripperWeb/bedrock"

# Language Settings
default_lang: 'en'
languages: ['en']

# Reading Files
include:
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .editorconfig
  - .eslintignore
  - .eslintrc.js
  - .jekyll-assets-cache
  - .sass-cache
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gemfile.lock
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - Makefile
  - bower.json
  - media.json
  - models.json
  - node_modules
  - old_media.json
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - sitemap.json
  - src
  - tmp
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - webpack.config.js
  - yarn.lock
  - yarn-error.log
keep_files:
  - .git
  - assets
  - ttio_templates/bedrock/assets
  - ttio_templates/zom/assets
  - ttio_templates/ivy/assets
  
rsync_copy:
  - _assets
  - _ttio_templates/bedrock/assets
  - _ttio_templates/zom/assets
  - _ttio_templates/ivy/assets
  
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  load_paths:
    - _sass
  style: compressed

# Outputting
permalink: pretty
timezone: # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones

